#!/usr/bin/env bash
#prints Best School if i != 4 and 8. 
#if -eq 4, print good luck, else print bad luck

c=0

while [ $c -lt 10 ]
do
	if [ $c -eq 3 ]
	then
		echo "bad luck"
	elif [ $c -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( c++ ))
done		 
