#!/usr/bin/env bash
#printing from 1 - 20 using while loop and case

i=1
while [ $i -lt 20 ]
do 
    case $i in 
    4)
    echo "$i"
    echo "bad luck from china";;
    9)
    echo "$i"
    echo "bad luck from Japan";;
    17)
    echo "$i"
    echo "bad luck from Italy";;
    *)
    echo "$i"
    esac
    (( i++ ))
done
